//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TUI.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TUI_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDD_PATIENT_INPUT_DIALOG        129
#define IDI_TABLE_1                     132
#define IDI_PATIENT                     133
#define IDD_TABLE_1101                  134
#define IDD_TABLE_DLG_1101              134
#define IDD_DIALOG1                     136
#define IDD_TABLE_1102                  136
#define IDD_TABLE_1201                  137
#define IDD_TABLE_1202                  138
#define IDD_TABLE_1203                  139
#define IDD_TABLE_1204                  140
#define IDD_TABLE_1205                  141
#define IDI_PATIENT_SEL                 142
#define IDD_TABLE_1206                  142
#define IDD_TABLE_1301                  143
#define IDI_TABLE_LOCK                  143
#define IDD_TABLE_1302                  144
#define IDD_TABLE_1303                  145
#define IDD_TABLE_1401                  146
#define IDD_TABLE_1402_1425             147
#define IDD_TABLE_1426                  148
#define IDD_TABLE_1                     149
#define IDD_TABLE_2001                  149
#define IDD_TABLE_2200                  150
#define IDD_TABLE_2300                  151
#define IDD_RESEARCH_INPUT_DIAGLOG      152
#define IDD_RESEARCH_TABLE_3            153
#define IDD_RESEARCH_TABLE_1            154
#define IDD_RESEARCH_TABLE_2            155
#define IDD_DATE_CONFIRM_DIALOG         156
#define IDD_STATS_DIALOG                157
#define IDD_IMPORT_DATA                 158
#define IDD_SAVE_LOAD_DATA_DLG          159
#define IDI_PATIENT_FINISHED            161
#define IDI_PATIENT_FINISHED_SEL        162
#define IDI_TABLE_FINISHED              163
#define IDI_LDY_PATIENT                 164
#define IDI_LDY_PATIENT_SEL             165
#define IDI_LDY_PATIENT_FINISHED_SEL    166
#define IDI_LDY_PATIENT_FINISHED        167
#define IDB_BK                          169
#define IDI_ICON1                       171
#define IDC_PATIENT_INPUT               1000
#define IDC_DISPLAY_BUTTON              1001
#define IDC_HEALTH_INFO_BUTTON          1002
#define IDC_TOWN_SEL_COMBO              1003
#define IDC_CITY_SEL_COMBO              1004
#define IDC_NEW_PATIENT                 1016
#define IDC_BUTTON10                    1025
#define IDC_DELETE_PATIENT              1025
#define IDC_TABLE_LIST                  1026
#define IDC_SUB_SECTION_TAB             1027
#define IDC_PATIENT_LIST                1028
#define IDC_ID                          1029
#define IDC_EXPORT_DATA                 1029
#define IDC_EDIT2                       1030
#define IDC_REGISTER_ID                 1030
#define IDC_CHECK_STAT                  1030
#define IDC_EDIT3                       1031
#define IDC_NAME                        1031
#define IDC_IMPORT_DATA                 1031
#define IDC_EDIT4                       1032
#define IDC_CONTACT_INFO                1032
#define IDC_COMBO1                      1033
#define IDC_SEX_COMBO                   1033
#define IDC_PROJECT_SEL                 1033
#define IDC_AGE                         1034
#define IDC_DATETIMEPICKER1             1035
#define IDC_HOW_LONG                    1035
#define IDC_LOCAL_LIVING_YEAR           1035
#define IDC_CURRENT_MONTH               1035
#define IDC_MONTH_SEL                   1035
#define IDC_EDIT5                       1036
#define IDC_ADDRESS                     1036
#define IDC_DOCTOR_NAME                 1036
#define IDC_EDIT6                       1037
#define IDC_BORN_ADDRESS                1037
#define IDC_DATETIMEPICKER2             1038
#define IDC_DIANOSTIC_DATE              1038
#define IDC_DATETIMEPICKER3             1039
#define IDC_REGISTER_DATE               1039
#define IDC_DATETIMEPICKER4             1040
#define IDC_PHLEGM_DATE                 1040
#define IDC_COMBO2                      1041
#define IDC_SCREEN_OBJECT               1041
#define IDC_COMBO3                      1042
#define IDC_CURE_CATEGORY               1042
#define IDC_TUB_HISTORY_YESNO           1042
#define IDC_COMBO4                      1043
#define IDC_REGISTER_CATEGORY           1043
#define IDC_IS_EXCLUDED_BY_X            1043
#define IDC_COMBO5                      1044
#define IDC_MEDCINE_HISTORY_CATEGORY    1044
#define IDC_CHRONIC_DISEASE_HISTORY     1044
#define IDC_DATETIMEPICKER5             1045
#define IDC_CURL_START_DATE             1045
#define IDC_RESPIRATORY_SYSTEM_DISEASE_YESNO 1045
#define IDC_SAMPLE_DATE                 1046
#define IDC_IS_AGREED                   1046
#define IDC_SECTION_TAB                 1047
#define IDC_SAMPLE_REPORT_DATE          1047
#define IDC_IS_OBSORBED                 1047
#define IDC_SAMPLE_RESULT               1048
#define IDC_IS_STAY_OUTSIDE             1049
#define IDC_CONFIRM                     1050
#define IDC_IS_ACCOMPANY                1051
#define IDC_CULTIVATE_DATE              1052
#define IDC_IS_STAY_OUTSIDE_ACCOMPANY   1052
#define IDC_REPORT_DATE                 1053
#define IDC_CULTIVATE_RESULT            1054
#define IDC_PATIENT_SEARCH_INFO_DATE    1054
#define IDC_EXAMINE_RESULT              1055
#define IDC_EXAMINE_START_DATE          1056
#define IDC_LFP_RESULT                  1056
#define IDC_DIAGNOSTIC_RESULT           1056
#define IDC_START_DATE                  1057
#define IDC_WILLING_TO_BE_SEARCHED      1057
#define IDC_YADC_RESULT                 1058
#define IDC_PATIENT_SEARCH_INFO         1058
#define IDC_LMS_RESULT                  1059
#define IDC_KNMS_RESULT                 1060
#define IDC_YFSX_RESULT                 1061
#define IDC_YYJ_RESULT                  1062
#define IDC_NDY_REGISTER_NO             1063
#define IDC_IS_SUITABLE                 1064
#define IDC_IS_ACKED                    1065
#define IDC_IS_QUESTIONAIR_FINISHED     1066
#define IDC_FINISHED_DATE               1067
#define IDC_IS_QUESTIONAIR_COMPLETE     1068
#define IDC_IS_BLOOD_TAKEN              1069
#define IDC_BLOOD_TAKEN_DATE            1070
#define IDC_BLOOD_TAKEN_NO              1071
#define IDC_BLOOD_ML                    1072
#define IDC_IS_RESERVED_20              1073
#define IDC_IS_TO_PROVINCE              1073
#define IDC_IS_RESERVED_4               1074
#define IDC_TO_PROVINCE_DATE            1074
#define IDC_INSTITUTION_LEVEL           1075
#define IDC_IS_TO_NATIONAL              1075
#define IDC_TO_NATIONAL_DATE            1076
#define IDC_IS_IN_HOSPITAL              1076
#define IDC_PROJECT                     1077
#define IDC_IN_HOSPITAL_DAY             1077
#define IDC_FIRST_TREAT_DATE            1078
#define IDC_WEIGHT                      1078
#define IDC_ABNORMAL_TYPE               1079
#define IDC_ABNORMAL_LEVEL              1080
#define IDC_ABNORMAL_DATE               1081
#define IDC_IMPACT                      1082
#define IDC_IS_PROJECT_CHANGED          1083
#define IDC_PROJECT_CHANGED_DATE        1084
#define IDC_CHANGED_PROJECT             1085
#define IDC_Z_YESNO                     1086
#define IDC_E_YESNO                     1087
#define IDC_KM_YESNO                    1088
#define IDC_AM_YESNO                    1089
#define IDC_CM_YESNO                    1090
#define IDC_LFX_YESNO                   1091
#define IDC_MFX_YESNO                   1092
#define IDC_PTO_YESNO                   1093
#define IDC_CS_YESNO                    1094
#define IDC_PAS_YESNO                   1095
#define IDC_OFX_YESN                    1097
#define IDC_ALTER_TYPE                  1097
#define IDC_OTHER_MEDICINE              1098
#define IDC_ALTER_DATE                  1098
#define IDC_HOW_FAR                     1099
#define IDC_BY_WHAT_VEHICLE             1100
#define IDC_FEE_FOR_VEHICLE             1101
#define IDC_FEE_FOR_STAY_OUTSIDE        1102
#define IDC_HOW_MANY_DINNERS            1103
#define IDC_FEE_FOR_DINNER              1104
#define IDC_HOW_MANY_ACCOMPANY          1105
#define IDC_FEE_FOR_VEHICLE_ACCOMPANY   1106
#define IDC_FEE_FOR_STAY_OUTSIDE_ACCOMPANY 1107
#define IDC_HOW_MANY_DINNERS_ACCOMPANY  1108
#define IDC_FEE_FOR_DINNER_ACCOMPANY    1109
#define IDC_DOCTOER_NAME                1110
#define IDC_FILLING_DATE                1111
#define IDC_EXPENSE_FOR_TRAVAL          1112
#define IDC_EXPENSE_FOR_ACCOMMODATION   1113
#define IDC_MEDICARE_ACTUAL_REIMBURSEMENT 1114
#define IDC_GLOBAL_FUND_REIMBURSEMENT   1115
#define IDC_OTHER_COMMERCIAL_REIMBURSEMENT 1116
#define IDC_PERSONAL_PAID               1117
#define IDC_OTHER_SOURCE                1118
#define IDC_IN_HOSPITAL_NO              1119
#define IDC_ACTUAL_TOTAL                1120
#define IDC_EXPENSE_FOR_BED             1121
#define IDC_EXPENSE_FOR_NURSING_CARE    1122
#define IDC_EXPENSE_DIAGNOS             1123
#define IDC_EXPENSE_OTHER_ASSAY         1124
#define IDC_ANTI_TUB_MEDICINE           1125
#define IDC_EXPENSE_FOR_ASSISTANT_MEDICINE 1126
#define IDC_EXPENSE_SURGERY             1127
#define IDC_EXPENSE_OTHERS              1128
#define IDC_MEDICAL_CARE_CATEGORY       1129
#define IDC_EXPENSE_RANDOM_CHECK        1131
#define IDC_EXPENSE_FOR_INJECTION       1132
#define IDC_FILTER                      1135
#define IDC_EXPORT_PROGRESS             1136
#define IDC_STATIC_EXPORT               1137
#define IDC_CUR_INPUT_DATE              1148
#define IDC_DATE_INPUT                  1149
#define IDC_STATS_TWO                   1151
#define IDC_STATS_ONE                   1152
#define IDC_IND_LIST                    1152
#define IDC_CONFLICT_INFO_LIST          1153
#define IDC_IMPORT_PROGRESS             1154
#define IDC_STATIC_TIP                  1155
#define IDC_IND_OK_LIST                 1156
#define IDC_LOAD_DATA_PROGRESS          1157
#define IDC_STATIC_PATIENT_LIST         1158
#define IDC_STATIC_CT                   1159
#define IDC_STATIC_FILTER               1160
#define IDC_STATIC_LIST                 1161
#define IDC_EXPORT                      1169
#define IDC_STATIC_BK                   1170

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1175
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
